### ISSUE TITLE
Another crash on exit

### ISSUE THREAD

**Issue by AMDmi3** [juzzlin/DustRacing2D#23]
1.13.0 still crashes on exit. This may not be related to #19 since the trace is different, and that issue is closed anyway, so here's the new issue with actual trace:

```
[Fri Sep 15 22:53:17 2017] I:   Found '/usr/local/share/dustrac/levels/straight.trk', index=7
[Fri Sep 15 22:53:17 2017] I:   Found '/usr/local/share/dustrac/levels/suzuka.trk', index=11
[Fri Sep 15 22:53:17 2017] I:   Found '/usr/local/share/dustrac/levels/triangle.trk', index=5
[Fri Sep 15 22:53:17 2017] I:   Found '/usr/local/share/dustrac/levels/Twineburg.trk', index=18
[Fri Sep 15 22:53:17 2017] I:   Found '/usr/local/share/dustrac/levels/twister.trk', index=10
[Fri Sep 15 22:53:17 2017] I:   Found '/usr/local/share/dustrac/levels/Western Valley.trk', index=16
[Fri Sep 15 22:53:17 2017] I: Loading race tracks from '/home/marakasov/DustRacingTracks'..
[Fri Sep 15 22:53:17 2017] I:   No race tracks found.
[Fri Sep 15 22:53:17 2017] I: A total of 15 race track(s) loaded.
[Fri Sep 15 22:53:22 2017] I: Quit selected from the main menu.
[LWP 100229 of process 62510 exited]
[LWP 101813 of process 62510 exited]

Thread 1 received signal SIGBUS, Bus error.
0x00000000005961bd in QOpenGLFunctions::glDeleteProgram (this=0x812926708, program=13) at /usr/local/include/qt5/QtGui/qopenglfunctions.h:1334
1334	    d_ptr->f.DeleteProgram(program);
(gdb) bt
#0  0x00000000005961bd in QOpenGLFunctions::glDeleteProgram (this=0x812926708, program=13) at /usr/local/include/qt5/QtGui/qopenglfunctions.h:1334
#1  0x0000000000592194 in MCGLShaderProgram::~MCGLShaderProgram (this=0x812926700) at /usr/work/tmp/dustrac/work/DustRacing2D-1.13.0/src/game/MiniCore/Graphics/mcglshaderprogram.cc:128
#2  0x0000000000592389 in MCGLShaderProgram::~MCGLShaderProgram (this=0x812926700) at /usr/work/tmp/dustrac/work/DustRacing2D-1.13.0/src/game/MiniCore/Graphics/mcglshaderprogram.cc:127
#3  0x00000000004bc6b5 in std::__1::default_delete<MCGLShaderProgram>::operator() (this=0x8023e1bb8, __ptr=0x812926700) at /usr/include/c++/v1/memory:2397
#4  std::__1::__shared_ptr_pointer<MCGLShaderProgram*, std::__1::default_delete<MCGLShaderProgram>, std::__1::allocator<MCGLShaderProgram> >::__on_zero_shared (this=0x8023e1ba0) at /usr/include/c++/v1/memory:3795
#5  0x000000080332799b in std::__1::__shared_count::__release_shared (this=0x8023e1ba0) at /usr/src.git/contrib/libc++/src/memory.cpp:67
#6  std::__1::__shared_weak_count::__release_shared (this=0x8023e1ba0) at /usr/src.git/contrib/libc++/src/memory.cpp:92
#7  0x000000000042871c in std::__1::shared_ptr<MCGLShaderProgram>::~shared_ptr (this=0x8018d2180) at /usr/include/c++/v1/memory:4626
#8  0x000000000058e501 in MCGLScene::~MCGLScene (this=0x8018d2038) at /usr/work/tmp/dustrac/work/DustRacing2D-1.13.0/src/game/MiniCore/Graphics/mcglscene.cc:313
#9  0x00000000005aa8c3 in MCWorldRenderer::~MCWorldRenderer (this=0x8018d2000) at /usr/work/tmp/dustrac/work/DustRacing2D-1.13.0/src/game/MiniCore/Graphics/mcworldrenderer.cc:352
#10 0x000000000058411b in MCWorld::~MCWorld (this=0x8009800f0) at /usr/work/tmp/dustrac/work/DustRacing2D-1.13.0/src/game/MiniCore/Core/mcworld.cc:85
#11 0x000000000045f04f in Game::~Game (this=0x800980000) at /usr/work/tmp/dustrac/work/DustRacing2D-1.13.0/src/game/game.cpp:442
#12 0x000000000045f0d9 in Game::~Game (this=0x800980000) at /usr/work/tmp/dustrac/work/DustRacing2D-1.13.0/src/game/game.cpp:421
#13 0x0000000000476152 in std::__1::default_delete<Game>::operator() (this=0x7fffffffe6f8, __ptr=0x800980000) at /usr/include/c++/v1/memory:2397
#14 std::__1::unique_ptr<Game, std::__1::default_delete<Game> >::reset (this=0x7fffffffe6f8, __p=0x0) at /usr/include/c++/v1/memory:2603
#15 std::__1::unique_ptr<Game, std::__1::default_delete<Game> >::~unique_ptr (this=0x7fffffffe6f8) at /usr/include/c++/v1/memory:2571
#16 main (argc=1, argv=0x7fffffffe930) at /usr/work/tmp/dustrac/work/DustRacing2D-1.13.0/src/game/main.cpp:79
```

**Comment by juzzlin** [comment]
I cannot make it crash on Linux, but Valgrind reports some similar problems like "Invalid read size of 8" when exiting the game. I'll look into this again.

**Comment by juzzlin** [comment]
A fix for some related issues is now in the master branch. Please test if that works for you.

**Comment by AMDmi3** [comment]
No, the error is the same.

**Comment by devnexen** [comment]
Now I remember why on OpenBSD (with default base compiler which will be clang clang++/libc++ from 6.2 release) we disabled QOpenGLFunctions but with this last commit it seems it does not segfault anymore while the previous still did.

**Comment by AMDmi3** [comment]
Can finally confirm this. Yes, 2.0.3 exists cleanly.
